---
# tasks file for ansible-role-stretcher
- name: install unzip for unarchive module
  yum:
    name: unzip
  tags: stretcher

- name: detect stretcher is installed
  stat:
    path: /usr/local/bin/stretcher
  register: stretcher_bin
  tags: stretcher

- block:
  - name: download stretcher {{ STRETCHER_VERSION }}
    unarchive:
      src: https://github.com/fujiwara/stretcher/releases/download/{{ STRETCHER_VERSION }}/stretcher-{{ STRETCHER_VERSION }}-linux-amd64.zip
      dest: /tmp
      remote_src: yes
      owner: root
      group: root
      mode: '0755'
  - name: install stretcher
    command: mv /tmp/stretcher-{{ STRETCHER_VERSION }}-linux-amd64 /usr/local/bin/stretcher
  when: not stretcher_bin.stat.exists
  tags: stretcher

- name: detect consul conf directory
  stat:
    path: /etc/consul.d
  register: consul_conf_dir
  tags: stretcher

- name: copy consul conf file
  template:
    src: stretcher.json.j2
    dest: /etc/consul.d/stretcher.json
    owner: root
    group: root
    mode: '0644'
  notify: restart consul service
  when: consul_conf_dir.stat.exists
  tags: stretcher
