---
# tasks file for ansible-role-stretcher
- name: install unzip for unarchive module
  yum:
    name: unzip

- name: detect stretcher is installed
  stat:
    path: /usr/local/bin/stretcher
  register: stretcher_bin

- block:
  - name: download stretcher {{ STRETCHER_VERSION }}
    unarchive:
      src: https://github.com/fujiwara/stretcher/releases/download/{{ STRETCHER_VERSION }}/stretcher-{{ STRETCHER_VERSION }}-linux-amd64.zip
      dest: /tmp
      remote_src: yes
      owner: root
      group: root
      mode: '0755'

  - name: install stretcher
    command: mv /tmp/stretcher-{{ STRETCHER_VERSION }}-linux-amd64 /usr/local/bin/stretcher

  when: not stretcher_bin.stat.exists

- name: detect consul conf directory
  stat:
    path: /etc/consul.d
  register: consul_conf_dir

- name: copy consul conf file
  template:
    src: stretcher.json.j2
    dest: /etc/consul.d/stretcher.json
    owner: root
    group: root
    mode: '0644'
  notify: restart consul service
  when: consul_conf_dir.stat.exists

- block:
  - name: copy stretcher autorun service file
    template:
      src: stretcher-autorun.service.j2
      dest: /etc/systemd/system/stretcher-autorun.service
      owner: root
      group: root
      mode: '0644'

  - name: daemon-reload
    systemd: daemon_reload=yes

  - name: start stretcher-autorun service
    service:
      name: stretcher-autorun
      state: started
      enabled: yes

  when: not stretcher_bin.stat.exists and stretcher_autorun_manifest != None
